# BullSaddle — Developed by Orion Impact (https://orion-impact.com)
# Licensed under the Apache License, Version 2.0.
# SPDX-License-Identifier: Apache-2.0

[advisories]
unmaintained = "workspace"
unsound = "all"

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = false
unused = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
    "Zlib",
]
