# BullSaddle — Developed by Orion Impact (https://orion-impact.com)
# Licensed under the Apache License, Version 2.0.
# SPDX-License-Identifier: Apache-2.0

[toolchain]
channel = "1.98.1"
profile = "minimal"
components = [
    "clippy",
    "rust-src",
    "rustfmt",
    "rust-analyzer",
]
