# BullSaddle — Developed by Orion Impact (https://orion-impact.com)
# Licensed under the Apache License, Version 2.0.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "bulls-application"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
bulls-core.workspace = true
serde.workspace = true

[dev-dependencies]
toml.workspace = true

[lints]
workspace = true
