# BullSaddle — Developed by Orion Impact (https://orion-impact.com)
# Licensed under the Apache License, Version 2.0.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "bulls-runtime"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
bulls-application.workspace = true
bulls-infra.workspace = true

[lints]
workspace = true
